### Get all hotels
GET http://localhost:7000/hotels/
Content-Type: application/json

### Create a new hotel with rooms
POST http://localhost:7000/hotels/hotel/
Content-Type: application/json

{
  "hotel_name": "Ocean Breeze Hotel",
  "hotel_address": "Seaside Blvd 12",
  "rooms": [
    {
      "room_number": 101,
      "room_price": 1500
    },
    {
      "room_number": 202,
      "room_price": 2200
    }
  ]
}

### Create a new hotel with rooms
POST http://localhost:7000/hotels/hotel/
Content-Type: application/json

{
  "hotel_name": "City Central Inn",
  "hotel_address": "Main Street 89",
  "rooms": [
    {
      "room_number": 305,
      "room_price": 1300
    },
    {
      "room_number": 412,
      "room_price": 1900
    }
  ]
}

### Create a new hotel with rooms
POST http://localhost:7000/hotels/hotel/
Content-Type: application/json

{
  "hotel_name": "Mountain View Lodge",
  "hotel_address": "Alpine Road 37",
  "rooms": [
    {
      "room_number": 105,
      "room_price": 1800
    },
    {
      "room_number": 207,
      "room_price": 2500
    }
  ]
}

### Get a hotel by ID
GET http://localhost:7000/hotels/hotel/3
Content-Type: application/json

### Update a hotel by ID
PUT http://localhost:7000/hotels/hotel/5
Content-Type: application/json

{
  "hotel_name": "Grand Bazar Hotel",
  "hotel_address": "Silk Road 37",
  "rooms": [
    {
      "room_number": 45,
      "room_price": 5400
    },
    {
      "room_number": 68,
      "room_price": 6700
    }
  ]
}

### Delete a hotel by id
DELETE http://localhost:7000/hotels/hotel/3
Content-Type: application/json

### Get all rooms for all hotels (not specified to a certain hotel even though the endpoint takes a hotel id)
GET http://localhost:7000/hotels/hotel/3/rooms/
Content-Type: application/json
